# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.env.enable
  config.vm.box_check_update = false
  config.vm.provision "shell", path:"role_all_vms.sh"

  config.vm.define "zbxdb" do |zbxdb|
    zbxdb.vm.box = ENV['BOX_NAME']
    zbxdb.vm.hostname = ENV['SRV_HOSTNAME']

    zbxdb.vm.network "public_network", :bridge => ENV['INTERFACE_BRIDGE_HOST_FISICO'], ip: ENV['SRV_IP']

    zbxdb.vm.provider "virtualbox" do |vb|
      vb.name = ENV['SRV_HOSTNAME']
      vb.memory = ENV['SRV_RAM']
      vb.cpus = ENV['SRV_CPU']
      vb.customize ["modifyvm", :id, "--groups", "/zabbix5-ALL-IN-ONE"]
    end
    zbxdb.vm.provision "shell", path: "role_bd.sh"
    zbxdb.vm.provision "shell", path: "role_zabbix.sh"
  end
end