# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.env.enable
  config.vm.box_check_update = false
  config.vm.provision "shell", path:"role_all_vms.sh"

  # Zabbix database
  config.vm.define ENV['MYSQL_HOSTNAME'] do |dbnfs|
    dbnfs.vm.box = ENV['BOX_NAME']
    dbnfs.vm.hostname = ENV['MYSQL_HOSTNAME']
    dbnfs.vm.network "public_network", :bridge => ENV['INTERFACE_BRIDGE_HOST_FISICO'], ip: ENV['SRV_DB_IP']

    dbnfs.vm.provider "virtualbox" do |vb|
      vb.name = ENV['MYSQL_HOSTNAME']
      vb.memory = ENV['MYSQL_RAM']
      vb.cpus = ENV['MYSQL_CPU']
      vb.customize ["modifyvm", :id, "--groups", ENV['VBOX_GROUP_NAME']]
    end
    dbnfs.vm.provision "shell", path: "role_nfs_server.sh"
    dbnfs.vm.provision "shell", path: "role_db.sh"
  end

  # Zabbix server + frontend + grafana
  config.vm.define ENV['DOCKER_HOSTNAME'] do |docker|
    docker.vm.box = ENV['BOX_NAME']
    docker.vm.hostname = ENV['DOCKER_HOSTNAME']
    docker.vm.network "public_network", :bridge => ENV['INTERFACE_BRIDGE_HOST_FISICO'], ip: ENV['DOCKER_SRV_IP']

    docker.vm.provider "virtualbox" do |vb|
      vb.name = ENV['DOCKER_HOSTNAME']
      vb.memory = ENV['DOCKER_RAM']
      vb.cpus = ENV['DOCKER_CPU']
      vb.customize ["modifyvm", :id, "--groups", ENV['VBOX_GROUP_NAME']]
    end
    docker.vm.provision "shell", path: "role_nfs_client.sh"
    docker.vm.provision "shell", path: "role_docker.sh"
    docker.vm.provision "shell", path: "role_swarm_deploy.sh"
  end

end
