# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.env.enable
  config.vm.box_check_update = false
  config.vm.provision "shell", path:"role_all_vms.sh"

  # Zabbix database
  config.vm.define ENV['MYSQL_HOSTNAME'] do |zbxdb|
    zbxdb.vm.box = ENV['BOX_NAME']
    zbxdb.vm.hostname = ENV['MYSQL_HOSTNAME']
    zbxdb.vm.network "public_network", :bridge => ENV['INTERFACE_BRIDGE_HOST_FISICO'], ip: ENV['SRV_BD_IP']

    zbxdb.vm.provider "virtualbox" do |vb|
      vb.name = ENV['MYSQL_HOSTNAME']
      vb.memory = ENV['MYSQL_RAM']
      vb.cpus = ENV['MYSQL_CPU']
      vb.customize ["modifyvm", :id, "--groups", "/zabbix5-DOCKER-ALL-IN-ONE"]
    end
    zbxdb.vm.provision "shell", path: "role_db.sh"
  end

  # Zabbix server + frontend + grafana
  config.vm.define ENV['ZBX_HOSTNAME'] do |zbxsrv|
    zbxsrv.vm.box = ENV['BOX_NAME']
    zbxsrv.vm.hostname = ENV['ZBX_HOSTNAME']
    zbxsrv.vm.network "public_network", :bridge => ENV['INTERFACE_BRIDGE_HOST_FISICO'], ip: ENV['ZABBIX_SRV_IP']

    zbxsrv.vm.provider "virtualbox" do |vb|
      vb.name = ENV['ZBX_HOSTNAME']
      vb.memory = ENV['ZBX_RAM']
      vb.cpus = ENV['ZBX_CPU']
      vb.customize ["modifyvm", :id, "--groups", "/zabbix5-DOCKER-ALL-IN-ONE"]
    end
    zbxsrv.vm.provision "shell", path: "role_docker_zbx.sh"
  end

end
